### PR TITLE
BETA Pull Request

### PR DESCRIPTION
**Pull request by RskFctr**
The Beta is currently undergoing testing by an enterprise team under my supervision.  I hope to have results from that team within a few weeks.  I consider this Beta suitable for release to the general public with an understanding that it is a "BETA".  The VSIX can be run in parallel to the older Add-in code base.  I am unsure of the versioning schema that the team has used for WSCF.blue in the past.  If semantic versioning is being used then the changes to the Connect class would require this release to increment the major version.

### CODE REVIEW

**Comment by alexmg** [comment]
Hi @RskFctr. I was going through some old emails and found a notification for this PR. Sorry that it has sat here for so long. It wouldn't have if I knew it was here! I'll take a look over it.

We probably should have created a develop branch for new work. Would you be able to PR into a develop branch if I create one? I will tag the current master branch at 1.0.14 regardless.

Hope you are still keen to push this forward. Sorry again for the really long delay.

**Comment by alexmg** [comment]
I tagged master at v1.0.14 (not actually released but was latest version at master) and created a develop branch.

**Comment by dojo87** [comment]
@RskFctr, great work! I will ask the developers I'm working with to try it out. We are looking at upgrading Visual Studio and the limit of last WSCF.Blue was the last blocker. 
@alexmg Any perspectives on your side for this pull request?

**Comment by alexmg** [comment]
I have merged the changes in and will take a look.

**Comment by alexmg** [comment]
Thanks for your work on this @RskFctr. I have created a [2.1.0 release](https://github.com/WSCF/WSCF/releases/tag/v2.1.0) with a VSIX package.

**Comment by NelsonRothermel** [comment]
FYI, a year or two ago I ran this version through several WSDLs and XSDs we had in Visual Studio 2015.  I didn't test all sets of configurations, but at least in our case it generated identical functional output in dozens/hundreds of classes.  There were some insignificant areas that differed which I think it were version numbers in attributes.

**Pull request merged**
